Sales/Sales.ApplicationWebLayer/Models/ShoppingCartViewModel.cs
using System.Collections.Generic;

namespace Sales.ApplicationWebLayer.Models
{
    public class ShoppingCartViewModel
    {
        public List<ShoppingCartItemViewModel> CartItems { get; set; }

        public ShoppingCartViewModel()
        {
            CartItems = new List<ShoppingCartItemViewModel>();
        }
    }
}

Sales/Sales.ApplicationWebLayer/Components/ShoppingCartViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Sales.ApplicationWebLayer.Helpers;
using Sales.ApplicationWebLayer.Models;
using Sales.BusinessLayer.Interfaces;

namespace Sales.ApplicationWebLayer.Components
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IShoppingCartService _shoppingCartService;

        public ShoppingCartViewComponent(IShoppingCartService shoppingCartService)
        {
            _shoppingCartService = shoppingCartService;
        }

        public IViewComponentResult Invoke()
        {
            var userId = Guid.Parse(User.Identity.Name);

            var cartItems = GetCartItems(userId);

            var shoppingCart = new ShoppingCartViewModel
            {
                CartItems = cartItems
            };

            return View($"ShoppingCart", shoppingCart);
        }

        private List<ShoppingCartItemViewModel> GetCartItems(Guid userId)
        {
            var items = _shoppingCartService.GetOrderedBooks(userId).Select(Mapper.Map).ToList();
            for (int i = 0; i < items.Count; i++)
            {
                items[i].Id = i + 1;
            }

            return items;
        }
    }
}

Sales/Sales.ApplicationWebLayer/Controllers/MainPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sales.ApplicationWebLayer.Helpers;
using Sales.ApplicationWebLayer.Models;
using Sales.BusinessLayer.Interfaces;

namespace Sales.ApplicationWebLayer.Controllers
{
    [Authorize]
    public class MainPageController : Controller
    {
        private readonly IBookService _bookService;
        private readonly IShoppingCartService _shoppingCartService;
        private readonly IOrderService _orderService;

        public MainPageController(IBookService bookService, IShoppingCartService shoppingCartService, IOrderService orderService)
        {
            _bookService = bookService;
            _shoppingCartService = shoppingCartService;
            _orderService = orderService;
        }

        public IActionResult Index()
        {
            var userId = User.Identity.Name;
            ViewData["UserId"] = userId;

            var orderedItems = GetOrderedBooks(userId);

            return View(orderedItems);
        }

        [HttpPost]
        [AllowAnonymous]
        public IActionResult AddToCart(int bookId)
        {
            var userId = Guid.Parse(User.Identity.Name);

            _bookService.DecrementCopiesNumber(bookId);
            _shoppingCartService.AddBookToCart(bookId, userId);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult RemoveFromCart(int bookId)
        {
            var userId = Guid.Parse(User.Identity.Name);

            _bookService.IncrementCopiesNumber(bookId);
            _shoppingCartService.RemoveBookFromCart(bookId, userId);

            return RedirectToAction("Index");
        }

        private List<BookViewModel> GetOrderedBooks(string userId)
        {
            var orderedItems = _shoppingCartService.GetOrderedBooks(Guid.Parse(userId));
            var books = _bookService.GetAllBooks().Select(Mapper.Map).ToList();

            foreach (var orderedBook in orderedItems)
            {
                books.First(b => b.Id == orderedBook.BookId).HasAlreadyInCart = true;
            }

            return books;
        }

        [HttpPost]
        public IActionResult MakeOrder(string orderedBookIds)
        {
            var userId = Guid.Parse(User.Identity.Name);

            _orderService.CreateOrder(userId, orderedBookIds);

            HttpContext.SignOutAsync();

            return RedirectToAction("Index", "StartPage");
        }
    }
}

Sales/Sales.ApplicationWebLayer/Views/MainPage/Components/ShoppingCart/ShoppingCart.cshtml
@model Sales.ApplicationWebLayer.Models.ShoppingCartViewModel

<head>
    <script src="~/js/signalr/dist/browser/signalr.min.js" asp-append-version="true"></script>
    <script>
    const hubConnection = new signalR.HubConnectionBuilder()
    .withUrl("/bookCounterHub")
    .build();

    hubConnection.on("UpdateRemainCopiesNumber", function(bookId, changeValue) {
        let elemValue = document.getElementById(bookId).firstChild;
        let nodeValue = elemValue.nodeValue;
        let newValue = parseInt(changeValue) + parseInt(nodeValue);
        elemValue.replaceData(0, elemValue.length, newValue);
        });
    hubConnection.start();

    function increaseRemainingCopies(id) {
        hubConnection.invoke("UpdateRemainCopiesNumber", id, -1);
    }

    </script>
</head>
<body>
<h2>
    Корзина
</h2>
<table class="table">
    <th>
        Позиция
    </th>
    <th>
        Название
    </th>
    <th>
        Цена
    </th>
    @using (Html.BeginForm())
    {
        @foreach (var cartItem in Model.CartItems)
        {
            <tr>
                <td>
                    @cartItem.Id
                </td>
                <td>
                    @cartItem.BookTitle
                </td>
                <td>
                    @cartItem.BookPrice
                </td>
                <td>
                    <form asp-action="RemoveFromCart">
                        <button asp-action="RemoveFromCart" type="submit" asp-route-bookId="@cartItem.BookId" onclick="increaseRemainingCopies(@cartItem.BookId)" class="btn btn-outline-secondary">убрать</button>
                    </form>
                </td>
            </tr>
        }
    }
</table>
<div>
    Итоговая сумма: @Model.CartItems.Sum(i => i.BookPrice)
    @if (Model.CartItems.Sum(i => i.BookPrice) >= 2000)
    {
        <form asp-action="MakeOrder" asp-controller="MainPage">
            <button asp-action="MakeOrder" type="submit" asp-route-orderedBookIds ="@string.Join(",",Model.CartItems.Select(i => i.BookId))" class="btn btn-outline-secondary">Оформить заказ</button>
        </form>
    }
</div>

</body>